---
kind: pipeline
type: docker
name: Building..
platform:
  os: linux
  arch: armv8
node:
  drone: bzk
steps:
- name: download latest Unimus-core
  image: alpine:latest
  commands:
    - apk add --no-cache wget
    - wget -O /drone/src/files/Unimus-Core.jar https://download.unimus.net/unimus-core/-%20Latest/Unimus-Core.jar
- name: build & push
  image: plugins/docker
  settings:
    repo: smartinfrasolutions/unimus-core
    tags: [ "latest" ]
    username: smartinfrasolutions
    password:
      from_secret: dockerhub_token
- name: notification
  image: plugins/webhook
  settings:
    urls:
      from_secret: webhookgotify
    content_type: application/json
    template: |
      {
       "message": "{{ repo.owner }} as updated {{ repo.name }} with {{ build.status }}.",
       "priority": 4,
       "title": "{{ repo.name }} build"
      }
  when:
    status: [success, failure]
---
kind: signature
hmac: 08ca9b245fb16ad8304a1596452a79af89f1db27bdadd33a4055e42818d5428e

...
