FROM debian:11-slim

# Set Unimus lated download url
ENV DOWNLOAD_URL https://download.unimus.net/unimus-core/-%20Latest/Unimus-Core.jar

# Update & install
RUN apt-get update && \
    apt-get install -y curl tini less wget tzdata openjdk-11-jre-headless && \
    apt-get clean && \
    apt-get autoremove --yes && \
# Unimus binary download
    curl -L -o /opt/unimus-core.jar $DOWNLOAD_URL && \
# Remove apt cache
    rm -rf /var/lib/{apt,dpkg,cache,log}/

# Copy all files (start.sh) into the container image
COPY files/* /opt/

# Add script permission
RUN chmod +x /opt/start.sh

# Entrypoint
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/opt/start.sh"]