---
version: "3"

services:
  unimus-core:
    image: Smart-Infra-Solutions/docker-unimus-core
    environment:
      # unimus server address
      - UNIMUS_SERVER_ADDRESS=xxx.xxx.xxx.xxx
      - UNIMUS_SERVER_PORT=5509
      - UNIMUS_SERVER_ACCESS_KEY=i...........................................................................p
      # base memory params for java
      - XMX=1024M
      - XMS=256M
      # OR more customizable JAVA options
      # - JAVA_OPTS=-Xms128M -Xmx512M
      - TZ=Europe/Paris
    volumes:
      - './config:/etc/unimus-core'
      - '/etc/localtime:/etc/localtime:ro'
    restart: unless-stopped
