FROM azul/zulu-openjdk-alpine:25-latest

# Set Unimus latest download url
ENV DOWNLOAD_URL=https://download.unimus.net/unimus-core/-%20Latest/Unimus-Core.jar

# Update & install
RUN apk update && \
    apk add --no-cache less curl tini wget tzdata && \
# Unimus binary download
    curl -L -o /opt/unimus-core.jar $DOWNLOAD_URL && \
# Remove apk cache
    rm -rf /var/cache/apk/*

# Copy all files (start.sh) into the container image
COPY files/* /opt/

# add script permission
RUN chmod +x /opt/start.sh

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
    CMD pgrep -f "unimus-core.jar" || exit 1

# Entrypoint
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["/opt/start.sh"]
