FROM alpine:3.17

# Set Unimus lated download url
ENV DOWNLOAD_URL https://download.unimus.net/unimus-core/-%20Latest/Unimus-Core.jar

# Update & install
RUN apk update && \
    apk add --no-cache less curl tini wget tzdata openjdk11-jre-headless && \
# Unimus binary download
    curl -L -o /opt/unimus-core.jar $DOWNLOAD_URL && \
# Remove apk cache
    rm -rf /var/cache/apk/*

# Copy all files (start.sh) into the container image
COPY files/* /opt/

# add script permission
RUN chmod +x /opt/start.sh

# Entrypoint
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["/opt/start.sh"]
