FROM debian:stable-slim

# Set Unimus latest download url
ENV DOWNLOAD_URL=https://download.unimus.net/unimus-core/-%20Latest/Unimus-Core.jar

# Update & install
RUN apt-get update && \
    apt-get install -y curl tini less wget tzdata openjdk-25-jre-headless && \
    apt-get clean && \
    apt-get autoremove --yes && \
# Unimus binary download
    curl -L -o /opt/unimus-core.jar $DOWNLOAD_URL && \
# Remove apt cache
    rm -rf /var/lib/{apt,dpkg,cache,log}/

# Copy all files (start.sh) into the container image
COPY files/* /opt/

# Add script permission
RUN chmod +x /opt/start.sh

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
    CMD pgrep -f "unimus-core.jar" || exit 1

# Entrypoint
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/opt/start.sh"]
