---
depends_on: [alpine, debian]
when:
  - event: [pull_request, tag]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:

  - name: link-validation
    image: docker.io/lycheeverse/lychee
    commands:
      - lychee --no-progress --format detailed README.md
